#spring.application.name=ai-analizer
#
#spring.ai.google.api-key=AIzaSyCsF5LosDRD_WNB41E4Svd3uCoqzRahrh0
#spring.ai.google.chat.options.model=gemini-1.5-pro
#
#server.port=8081

spring:
  application:
    name: ai-analyzer

  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY} # Gemini API key
        api-key-only: true                # <-- MUST set this
        chat:
          options:
            model: gemini-2.5-flash
            temperature: 0.7

server:
  port: 8082

logging:
  level:
    org:
      springframework:
        ai:
          vertex:
            ai:
              gemini: DEBUG