spring:
  application:
    name: ai-analyzer

  datasource:
    url: jdbc:mysql://localhost:3306/ai_analyzer
    username: root
    password: rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: false

  ai:
    google:
      genai:
        api-key:  # Gemini API key
        api-key-only: true                # <-- MUST set this
        chat:
          options:
            model: gemini-2.5-flash
            temperature: 0.7

  # Outbox processing configuration
  outbox:
    batch-size: 1  # Number of records to process in each batch

  recordScheduler:
    pool:
      core-size: 1
      max-size: 1
      queue-capacity: 10000
    fixed-rate: 5000  #

server:
  port: 8082

logging:
  level:
    org:
      springframework:
        ai:
          vertex:
            ai:
              gemini: DEBUG